### ISSUE TITLE
Images - Add missing SizeGigabytes

### ISSUE THREAD

**Issue by ppumkin** [vevix/DigitalOcean.API#21]
I would like to know the size in gigabytes of the image/ snapshot

API shows 

> size_gigabytes | integer | The size of the image in gigabytes.

**Comment by ppumkin** [comment]
Please review PR

https://github.com/vevix/DigitalOcean.API/pull/22

I have tested locally and it bring back the Size in int

**Comment by ppumkin** [comment]
Thanks
When do you do nuget releases?

**Comment by vevix** [comment]
Probably tonight or tomorrow, assuming I don't throw my Windows PC out the window.

**Comment by ppumkin** [comment]
Hehehe - (post edit) Windows is not THAT bad 🚽  heheh
Thanks again
