### ISSUE TITLE
Cannot use NuGet to install into my new project.

### ISSUE THREAD

**Issue by chiangky** [vevix/DigitalOcean.API#24]
Hi, I have tried 
[1] Download this project source and open with VS2015, and
[2] Opened a new project and go to NuGet to install "DigitalOcean.API" in my project. (Although I changed my project's Target framework into .NET 2.0 or .NET 4.5.2, still got errors)
But seems all methods are not work for me. I don't know why, I have no ideas. Please advise with thanks!

For [1] ref:
![image](https://user-images.githubusercontent.com/37294789/37281062-b162feda-262a-11e8-8ac8-a5c8c5537f78.png)

For [2] ref: 
![image](https://user-images.githubusercontent.com/37294789/37281033-975d8e2e-262a-11e8-990c-6be10d396def.png)

**Comment by vevix** [comment]
version 2.0+ is targeted towards .NET Standard 2.0. That means you need to target .NET 4.6.1+ as this is the earliest version that implements support. 

If you're unable to target that then you may want to try installing a previous 1.x version which should also be available on NuGet

**Comment by chiangky** [comment]
Hello, thanks for your reply.

Do you mean I can install DigitalOcean.API v1.0.7 from NuGet using .NET Framework 4.6.1?
Is is compatible with existing APIs in document (i.e. https://developers.digitalocean.com/documentation/spaces/#bucket-ops)?

Below is my current setting, thanks.
![image](https://user-images.githubusercontent.com/37294789/37390483-37830e64-27a3-11e8-9929-9a83b84dd80c.png)

**Comment by vevix** [comment]
DigitalOcean.API v2.0 will work with .NET 4.6.1.

Neither version supports Buckets/Spaces as it isn't apart of the API. See #20
