### ISSUE TITLE
Support for portable .Net projects

### ISSUE THREAD

**Issue by jagbarrameda** [vevix/DigitalOcean.API#5]
The motivation is to have DigitalOcean Api clients for Windows Phone and Windows 8.1.
There are json serializers and Rest clients for portable .Net so it possible to make DigitalOcean.API a portable .Net project. I think of `SharpSerializer` (maybe Json supports has been added already, if not there are others) and `Microsoft.Net.HTTP` library (`https://www.nuget.org/packages/Microsoft.Net.Http`).

**Comment by vevix** [comment]
Thanks for the suggestion. I'll look into this when I have some free time!

**Comment by jagbarrameda** [comment]
Great!
Thank you for this project!
